version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=$ECR_REPO
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 542450504390.dkr.ecr.us-east-1.amazonaws.com  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd DevOps_2.0/M5/human-gov-application/src
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`  
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export imageTag=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '[{\"name\":\"humangov-app\",\"imageUri\":\"%s\"}]' $REPOSITORY_URI:$imageTag > imagedefinitions.json
      - cat imagedefinitions.json
      - ls -l
env:
  exported-variables: ["imageTag"]
  
artifacts:
  files: 
    - DevOps_2.0/M5/human-gov-application/src/imagedefinitions.json
    - DevOps_2.0/M5/human-gov-application/src/humangov-california.yaml
    - DevOps_2.0/M5/human-gov-application/src/humangov-florida.yaml
    - DevOps_2.0/M5/human-gov-application/src/humangov-staging.yaml